GET http://localhost:8080/ca1backend/api/person

###
POST http://localhost:8080/ca1backend/api/person
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"firstName": "First Property", "str2": "Second Property"}